/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness: the process is up. Used by the host to restart a dead service.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: the database answers.
         */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Data
         * @description Everything stored about the caller, as JSON.
         */
        get: operations["export_data_api_v1_users_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Account
         * @description Permanently delete the account and its data. Needs the password again.
         *
         *     A POST rather than DELETE because some clients and proxies drop DELETE bodies.
         */
        post: operations["delete_account_api_v1_users_me_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Setup */
        put: operations["put_setup_api_v1_profile_setup_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Cv
         * @description PDF or DOCX, up to 5 MB. Found skills come back as pending, for the user to confirm.
         */
        post: operations["upload_cv_api_v1_profile_cv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/cv/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_v1_profile_cv_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/cv/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_profile_cv_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_profile_cv_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommended */
        get: operations["recommended_api_v1_jobs_recommended_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Preview
         * @description Read a posting from a link. Nothing is saved.
         */
        post: operations["import_preview_api_v1_jobs_import_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Job */
        post: operations["import_job_api_v1_jobs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Job */
        get: operations["read_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Match */
        get: operations["read_match_api_v1_jobs__job_id__match_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /**
         * Create Application
         * @description Track a job (save it, or record that you applied). Sends nothing to the employer.
         */
        post: operations["create_application_api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Application */
        get: operations["read_application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_api_v1_applications__application_id__delete"];
        options?: never;
        head?: never;
        /** Update Application */
        patch: operations["update_application_api_v1_applications__application_id__patch"];
        trace?: never;
    };
    "/api/v1/applications/{application_id}/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Reminder */
        put: operations["set_reminder_api_v1_applications__application_id__reminder_put"];
        post?: never;
        /** Clear Reminder */
        delete: operations["clear_reminder_api_v1_applications__application_id__reminder_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_agent_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description Start a task. It runs in the background: poll GET /agent/tasks/{id} for progress.
         */
        post: operations["create_task_api_v1_agent_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_agent_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending */
        get: operations["list_pending_api_v1_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description The backend performs the action only after this call. The AI cannot approve itself.
         */
        post: operations["approve_api_v1_approvals__approval_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approvals/{approval_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_approvals__approval_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionRead */
        ActionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Step */
            step: number;
            /** Tool */
            tool: string;
            /** Permission */
            permission: string;
            /** Status */
            status: string;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /**
             * Jobid
             * Format: uuid
             */
            jobId: string;
            /** @default saved */
            status: components["schemas"]["ApplicationStatus"];
        };
        /** ApplicationRead */
        ApplicationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jobid */
            jobId: string | null;
            /** Jobtitle */
            jobTitle: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            status: components["schemas"]["ApplicationStatus"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Appliedat */
            appliedAt: string | null;
            /** Notes */
            notes: string;
            reminder: components["schemas"]["Reminder"] | null;
            /** Timeline */
            timeline: components["schemas"]["TimelineEvent"][];
            /** Matchscore */
            matchScore: number | null;
            matchLevel: components["schemas"]["MatchLevel"] | null;
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "saved" | "preparing" | "applied" | "interview" | "offer" | "rejected";
        /** ApplicationUpdate */
        ApplicationUpdate: {
            status?: components["schemas"]["ApplicationStatus"] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * ApprovalRead
         * @description What the app shows on the approval screen: the action, who or what it affects, a preview.
         */
        ApprovalRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Tool */
            tool: string;
            /** Permission */
            permission: string;
            /** Status */
            status: string;
            /** Preview */
            preview: {
                [key: string]: unknown;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** Body_upload_cv_api_v1_profile_cv_post */
        Body_upload_cv_api_v1_profile_cv_post: {
            /** File */
            file: string;
        };
        /** CvFileRead */
        CvFileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            fileName: string;
            /** Contenttype */
            contentType: string;
            /** Sizebytes */
            sizeBytes: number;
            /**
             * Uploadedat
             * Format: date-time
             */
            uploadedAt: string;
        };
        /** CvItemCreate */
        CvItemCreate: {
            section: components["schemas"]["CvSection"];
            /** Label */
            label: string;
            /** Detail */
            detail?: string | null;
        };
        /** CvItemRead */
        CvItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            section: components["schemas"]["CvSection"];
            /** Label */
            label: string;
            /** Detail */
            detail: string | null;
            /** Confidence */
            confidence: number;
            status: components["schemas"]["CvItemStatus"];
            /**
             * Origin
             * @enum {string}
             */
            origin: "cv" | "manual";
        };
        /**
         * CvItemStatus
         * @enum {string}
         */
        CvItemStatus: "pending" | "confirmed";
        /** CvItemUpdate */
        CvItemUpdate: {
            /** Label */
            label?: string | null;
            /** Detail */
            detail?: string | null;
            status?: components["schemas"]["CvItemStatus"] | null;
        };
        /**
         * CvSection
         * @enum {string}
         */
        CvSection: "skills" | "experience" | "education" | "certifications";
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /** DescriptionBlock */
        DescriptionBlock: {
            /**
             * Type
             * @enum {string}
             */
            type: "heading" | "paragraph" | "bullet";
            /** Text */
            text: string;
            /**
             * Requirement
             * @default false
             */
            requirement: boolean;
        };
        /**
         * EmploymentType
         * @enum {string}
         */
        EmploymentType: "full_time" | "part_time" | "contract" | "internship";
        /**
         * FactorStatus
         * @enum {string}
         */
        FactorStatus: "good" | "ok" | "poor" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportPreview
         * @description What was read from the link. Nothing is saved until the user confirms.
         */
        ImportPreview: {
            /** Url */
            url: string;
            /** Hostlabel */
            hostLabel: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            workMode: components["schemas"]["WorkMode"] | null;
            employmentType: components["schemas"]["EmploymentType"] | null;
            seniority: components["schemas"]["Seniority"] | null;
            salary: components["schemas"]["Salary"] | null;
            /** Postedat */
            postedAt: string | null;
            /** Summary */
            summary: string;
            /** Description */
            description: components["schemas"]["DescriptionBlock"][];
            /** Skills */
            skills: string[];
            /** Missing */
            missing: string[];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Url */
            url: string;
        };
        /** JobListItem */
        JobListItem: {
            job: components["schemas"]["JobRead"];
            match: components["schemas"]["MatchSummary"];
            /** Applicationid */
            applicationId?: string | null;
            applicationStatus?: components["schemas"]["ApplicationStatus"] | null;
        };
        /** JobRead */
        JobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Company */
            company: string;
            /** Location */
            location: string;
            workMode: components["schemas"]["WorkMode"] | null;
            employmentType: components["schemas"]["EmploymentType"] | null;
            seniority: components["schemas"]["Seniority"] | null;
            salary: components["schemas"]["Salary"] | null;
            source: components["schemas"]["JobSource"];
            /** Postedat */
            postedAt: string | null;
            /** Summary */
            summary: string;
            /** Description */
            description: components["schemas"]["DescriptionBlock"][];
            /** Skills */
            skills: string[];
        };
        /** JobSource */
        JobSource: {
            /** Label */
            label: string;
            /** Url */
            url: string;
            kind: components["schemas"]["JobSourceKind"];
        };
        /**
         * JobSourceKind
         * @enum {string}
         */
        JobSourceKind: "feed" | "imported";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchFactor */
        MatchFactor: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            status: components["schemas"]["FactorStatus"];
            /** Detail */
            detail: string;
        };
        /** MatchFactors */
        MatchFactors: {
            /** Deterministic */
            deterministic: components["schemas"]["MatchFactor"][];
            /** Ai */
            ai: components["schemas"]["MatchFactor"][];
        };
        /** MatchGap */
        MatchGap: {
            /** Label */
            label: string;
            /** Howtoclose */
            howToClose: string;
        };
        /**
         * MatchLevel
         * @enum {string}
         */
        MatchLevel: "strong" | "good" | "partial" | "weak";
        /** MatchRead */
        MatchRead: {
            /**
             * Jobid
             * Format: uuid
             */
            jobId: string;
            /** Score */
            score: number;
            level: components["schemas"]["MatchLevel"];
            /** Reason */
            reason: string;
            /** Strengths */
            strengths: string[];
            /** Gaps */
            gaps: components["schemas"]["MatchGap"][];
            factors: components["schemas"]["MatchFactors"];
            /** Basedon */
            basedOn: string[];
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
        };
        /** MatchSummary */
        MatchSummary: {
            /** Score */
            score: number;
            level: components["schemas"]["MatchLevel"];
        };
        /** ParsedCv */
        ParsedCv: {
            file: components["schemas"]["CvFileRead"];
            /**
             * Method
             * @enum {string}
             */
            method: "basic" | "ai";
            /** Items */
            items: components["schemas"]["CvItemRead"][];
            /** Notes */
            notes: string[];
        };
        /** ProfileRead */
        ProfileRead: {
            setup: components["schemas"]["SearchSetup"] | null;
            cv: components["schemas"]["CvFileRead"] | null;
            /** Items */
            items: components["schemas"]["CvItemRead"][];
            /** Completeness */
            completeness: number;
            /** Missing */
            missing: string[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /** Reminder */
        Reminder: {
            /**
             * Dueat
             * Format: date-time
             */
            dueAt: string;
            /** Note */
            note?: string | null;
        };
        /** Salary */
        Salary: {
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Currency */
            currency: string | null;
            period: components["schemas"]["SalaryPeriod"] | null;
            /** Text */
            text: string | null;
            /** Source */
            source: string;
        };
        /**
         * SalaryPeriod
         * @enum {string}
         */
        SalaryPeriod: "year" | "month" | "day" | "hour";
        /** SearchSetup */
        SearchSetup: {
            /**
             * Targetrole
             * @default
             */
            targetRole: string;
            /**
             * Location
             * @default
             */
            location: string;
            /** Salarymin */
            salaryMin?: number | null;
            /** Currency */
            currency?: string | null;
            salaryPeriod?: components["schemas"]["SalaryPeriod"] | null;
            seniority?: components["schemas"]["Seniority"] | null;
            /** Employmenttypes */
            employmentTypes?: components["schemas"]["EmploymentType"][];
            /** Workmodes */
            workModes?: components["schemas"]["WorkMode"][];
        };
        /**
         * Seniority
         * @enum {string}
         */
        Seniority: "intern" | "junior" | "mid" | "senior" | "lead";
        /** TaskCreate */
        TaskCreate: {
            /** Goal */
            goal: string;
        };
        /** TaskRead */
        TaskRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Goal */
            goal: string;
            /** Status */
            status: string;
            /** Result */
            result: string | null;
            /** Error */
            error: string | null;
            /** Steps Used */
            steps_used: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Actions
             * @default []
             */
            actions: components["schemas"]["ActionRead"][];
            pending_approval?: components["schemas"]["ApprovalRead"] | null;
        };
        /** TimelineEvent */
        TimelineEvent: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            kind: components["schemas"]["TimelineKind"];
            /** Text */
            text: string;
        };
        /**
         * TimelineKind
         * @enum {string}
         */
        TimelineKind: "saved" | "status" | "note" | "reminder";
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkMode
         * @enum {string}
         */
        WorkMode: "remote" | "hybrid" | "onsite";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    export_data_api_v1_users_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    delete_account_api_v1_users_me_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"];
                };
            };
        };
    };
    put_setup_api_v1_profile_setup_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchSetup"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSetup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cv_api_v1_profile_cv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_cv_api_v1_profile_cv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedCv"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_v1_profile_cv_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CvItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_profile_cv_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_profile_cv_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CvItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                q?: string | null;
                workModes?: components["schemas"]["WorkMode"][] | null;
                employmentTypes?: components["schemas"]["EmploymentType"][] | null;
                seniority?: components["schemas"]["Seniority"][] | null;
                minLevel?: components["schemas"]["MatchLevel"] | null;
                savedOnly?: boolean;
                sort?: "best_match" | "newest";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommended_api_v1_jobs_recommended_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItem"][];
                };
            };
        };
    };
    import_preview_api_v1_jobs_import_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_job_api_v1_jobs_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_match_api_v1_jobs__job_id__match_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"][];
                };
            };
        };
    };
    create_application_api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_v1_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_v1_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_reminder_api_v1_applications__application_id__reminder_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reminder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_reminder_api_v1_applications__application_id__reminder_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_agent_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"][];
                };
            };
        };
    };
    create_task_api_v1_agent_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_agent_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_api_v1_approvals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRead"][];
                };
            };
        };
    };
    approve_api_v1_approvals__approval_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_approvals__approval_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
